### ISSUE TITLE
Javascript Documentation

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#1000]
Debug, review, read and comment on the following files:

vendors
main
dfp
articles

purpose: to straighten up what is going on with ads and provide documentation for clarity

**Comment by ihciem** [comment]
Helpful documentation

- https://developers.google.com/publisher-tag/reference
- https://developers.google.com/publisher-tag/guides/control-ad-loading
- https://headerbidding.co/google-publisher-tag-gpt/
