### ISSUE TITLE
Ad Behavior - home page and base

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#1001]
Review home_page.html and base.html for lines where ad space and slugs are implemented. Debug and determine how code is functioning, use inspect tools firefox and scope out missing ad slots on homepage. If necessary rewrite ad inventory lines 40-43 and starting on line 56 article_list_sidebar_block.

Purpose: to ensure proper cpm are forecast in ad manager, all ad slots are displaying as expected, and code base is properly implemented.

**Comment by ihciem** [comment]
Ad manager settings tweaked. Ad slots weren't activated properly, etc. Closing.
