### ISSUE TITLE
Category design - taxonomy

### ISSUE THREAD

**Issue by keeganland** [ubyssey/ubyssey-dispatch-theme#1011]
Categories (FKA "subsections") as they were once designed implied relations between articles that didn't really exist which was very difficult to maintain. They currently exist in such a manner as to preserve the data that was intended insofar as is possible, but  these lack an explicit design contract and constantly generate complaints. 

A common way to implement website organization that categories are meant to capture is the "taxonomy" as is used in WordPress: https://developer.wordpress.org/themes/basics/categories-tags-custom-taxonomies/

While Wagtail does provide for hierarchy and for tagging, via treebeard and taggit respectively, an equivalent of the "taxonomy" abstraction does not exist out of the box. Given that there was a desire for articles to belong to not just a section but also a subsection (while still belonging to the section), and given that no relation was established between sections and subsections that precludes articles from belonging to any specific sections, we NEED some way to make the intended relations in the Category snippet useable. Patterns to solve this sort of problem exist, as demonstrated by the above WordPress link; we just don't use any such thing on our site.

(Example of why the the relations involving Categories are problematic: A subsection was supposed to belong to a section, but could contain articles from a completely unrelated section. For example, a subsection could belong to Sports, but contain articles from News).

An old post on the absence of taxonomy features out of the box in wagtail:
https://news.ycombinator.com/item?id=12224709
An example of more sophisticated taxonomy classes implemented into wagtail:
https://posts-by.lb.ee/building-a-configurable-taxonomy-in-wagtail-django-94ca1080fb28

The second of the above two links looks like something that would be desirable for our site.

**Comment by SamuelmdLow** [comment]
I think this is okay
