### ISSUE TITLE
Change icon/link on top right of homepage from Snapchat to Tiktok

### ISSUE THREAD

**Issue by ihciem** [ubyssey/ubyssey-dispatch-theme#1039]
Link to Ubyssey Tiktok: [https://www.tiktok.com/@ubyssey](https://www.tiktok.com/@ubyssey)

**Comment by wnguye03** [comment]
me and Deacon are working through this!

**Comment by FireBoyAJ24** [comment]
The homepage currently has links to Facebook, Instagram and Twitter. Do we want to add another link to Tiktok?

![image](https://user-images.githubusercontent.com/63443017/237057115-996ca63d-1ea8-4fd4-9466-b71c0fad25c9.png)

**Comment by SamuelmdLow** [comment]
I accomplish this in the redesign by updating our font-awesome
