### ISSUE TITLE
Gallery Block does not work

### ISSUE THREAD

**Issue by SamuelmdLow** [ubyssey/ubyssey-dispatch-theme#1117]
The Gallery block in the article content streamfield has a button to open the gallery. Clicking this button does nothing

**Comment by FireBoyAJ24** [comment]
`// 2022/05/25 - Galleries are a good idea, but broken. For all the below the best idea is likely "preserve and debug"`

A note made by Mei (I believe) within the article.jsx for functions which forms a gallery of pictures when a trigger occurs.

**Comment by SamuelmdLow** [comment]
![image](https://github.com/ubyssey/ubyssey.ca/assets/67992154/11742d78-691d-46a7-be2e-d63a7ec97bf1)
