### ISSUE TITLE
404 page is bad

### ISSUE THREAD

**Issue by SamuelmdLow** [ubyssey/ubyssey-dispatch-theme#1135]
Entering anything in the search box here https://ubyssey.ca/404/ it just redirects back to the 404 page

**Comment by PolMrt** [comment]
I'd like to work on this

**Comment by SamuelmdLow** [comment]
I fixed it so the 404 page doesn't give a 500 error now (lmao) but it does look very ugly. That still needs to be fixed!

**Comment by SamuelmdLow** [comment]
Our 404 page should say "404 Not found" . That should also be the header <title>. Here are some examples [vox](https://www.vox.com/404), [verge](https://www.theverge.com/404). 

I think it would also be cool if there was a "Was this what you were looking for?" section that used search to give a maximum of three articles that have similar titles to the query
