### ISSUE TITLE
Redundant Displays of section categories

### ISSUE THREAD

**Issue by FireBoyAJ24** [ubyssey/ubyssey-dispatch-theme#1227]
## What behavior were you expecting?
There are two category displays in the section page. We should explore removing one of them or changing the purpose of these two displays.
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/f534c3be-3b35-459c-8222-d4d1232f7ece) 
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/1e13cfbf-a3a4-47ca-8333-f9332eb2a40f)

**Comment by SamuelmdLow** [comment]
I think it will be better once editors remove old categories from the featured categories. I think they should only have about 3-5.
