### ISSUE TITLE
Adding filters to the section pages

### ISSUE THREAD

**Issue by FireBoyAJ24** [ubyssey/ubyssey-dispatch-theme#1228]
In the past we had a filter which ordered the articles based on the age of the article. After the new redesign (#1124) we have removed it. Could we find a way to add back this filter?

Reference:
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/388db93d-3ecc-4ceb-8d87-c21ed89513c6)

**Comment by SamuelmdLow** [comment]
I feel like this is a feature that only makes sense in the archive page. 99% of users probably don't have any interest in seeing articles from a decade ago so including it would just clutter the design
