### ISSUE TITLE
The Nav bar is not flush with the top of the browser

### ISSUE THREAD

**Issue by FireBoyAJ24** [ubyssey/ubyssey-dispatch-theme#1229]
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/db76d6cb-7184-4afa-84a8-9b7af0164085)

The picture and the text can be seen right above the nav bar. Can we please remove it?

**Comment by SamuelmdLow** [comment]
I tried all the browsers I have on my computer and couldn't see this. Is this error still appearing for you?

**Comment by SamuelmdLow** [comment]
I can't reproduce
