### ISSUE TITLE
Can't publish articles with emojis?

### ISSUE THREAD

**Issue by SamuelmdLow** [ubyssey/ubyssey-dispatch-theme#1439]
I think you can't publish things with a emojis in the rich text block. Thats sad so we should figure out if we can add that somehow

**Comment by Nishim12** [comment]
Editors can add emojis in Rich Text Block. They just need to do following commands:

### Windows:
1. Place your cursor in the Rich Text Block where you want to insert the emoji.
2. Press `Win + .` (Windows key and the period key) or `Win + ;` (Windows key and the semicolon key).
3. The emoji keyboard will pop up. Select the emoji you want to insert.

### Mac:
1. Place your cursor in the Rich Text Block where you want to insert the emoji.
2. Press `Control + Command + Space`.
3. The emoji keyboard will pop up. Select the emoji you want to insert.

Once you select an emoji, it will be inserted at the cursor position in the Rich Text Block.

**Comment by Nishim12** [comment]
https://dev.to/fabiocaccamo/how-to-use-emojis-in-a-python-django-mysql-project-1880

**Comment by Nishim12** [comment]
https://mathiasbynens.be/notes/mysql-utf8mb4 
The above link is for updating current tables and columns to convert utf8 charset to utf8mb4.

**Comment by SamuelmdLow** [comment]
This issue ocurred because the content from articles was placed into the the table used search which had a limited charset. I solved the issue by stopping the article content from going into the fields of that table. This maybe makes search worse.
