### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by jimmyhli** [ubyssey/ubyssey-dispatch-theme#166]
The date displayed in the website is incorrect. I suspect that it's UTC or some time zone in Europe/Asia because as of 20:46, Jan.05, 2016, the website has already displayed a date as Jan.06. An article that I read several hours ago showed a submission time of 1:45 am, Jan.06.

![untitled](https://cloud.githubusercontent.com/assets/18109953/21707905/6cecb55c-d388-11e6-9f82-6fe88ebe1f66.png)

**Comment by bennylojf** [comment]
Any hints as to where I can start looking for the source of the problem?

**Comment by psiemens** [comment]
@bennylojf Take a look through this documentation -- might be helpful: https://docs.djangoproject.com/en/1.10/topics/i18n/timezones/

**Comment by bennylojf** [comment]
I looked through that - seems like a backend issue. Does anyone know where/how the current time is generated? I looked through all the Python files but couldn't find the source of time.

**Comment by jimmyhli** [comment]
I believe that page.py is the one that imports datetime Object. I believe that you might need to specify the timezone in this case. @psiemens @bennylojf  what do you think about rendering time to users from different time zones? We can 1) display PST (B.C. time) to users from different timezone or 2) display time to users based on their timezone. By the way I remember that Django promotes the use of storing stuff in UTC and modify the time later sth

**Comment by bennylojf** [comment]
@HaoyuanLi  The datetime object is imported in views.py. I found 4 files that contain the term "datetime":

1) datetime.h
2) datetime_safe.py
3) humanize_datetime.py
4) DateTimeShortcuts.js

I am going to go through and experiment with these files to see if it leads me to a solution.

**Comment by jimmyhli** [comment]
@bennylojf  Good luck!

**Comment by psiemens** [comment]
@bennylojf Ah, I think I just figured it out. The timezone setting was being overridden in the Dispatch source code for some reason. Removing it allowed me to set the timezone manually to PST.

I'll take it from here. Thanks for looking into it -- sorry for the goose chase!

**Comment by blx** [comment]
i'm assuming this is the reason i'm seeing news from the future?

<img width="588" alt="screen shot 2017-10-10 at 10 36 53 pm" src="https://user-images.githubusercontent.com/887504/31423985-aabfc6e4-ae0c-11e7-8c07-68a642695a34.png">

**Comment by jumbosushi** [comment]
@psiemens I assume this is fixed so I'll close this
