### ISSUE TITLE
Improve video player, add play button

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#169]
The YouTube video player should be improved to display the title of the video, as well as a large, easy-to-click 'play' button in the center.

This is the current design:

![screen shot 2017-01-15 at 5 40 00 pm](https://cloud.githubusercontent.com/assets/2547035/21968452/b2d26062-db49-11e6-9bca-411019087d60.png)

**Comment by blx** [comment]
@psiemens I think it already does show the title, as long as a title was set when creating the embed. it looks like most of the current video embeds just don't have a title specified...

eg: (ignore play button)
![screen shot 2017-01-18 at 12 07 17 am](https://cloud.githubusercontent.com/assets/887504/22055889/2c9c91a0-dd12-11e6-9a3a-a646c2b68f23.png)

**Comment by psiemens** [comment]
@blx Ah you're right. It'd be nice to clean it up a bit still. I really like the NYT's video player design:

![screen shot 2017-01-18 at 7 53 25 am](https://cloud.githubusercontent.com/assets/2547035/22071206/4ed7d87e-dd53-11e6-9dab-3a755d1e32ff.png)

**Comment by napon** [comment]
Added in PR #175
