### ISSUE TITLE
Magazine: design article template

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#189]
The main components of the article template are:

**Header blocks**

* Headline
* Featured image
* Snippet
* Author byline/published date

**Content blocks**

* Paragraph
* Image
* Video
* Pull-quote
* Advertisement

**Comment by ghost** [comment]
Potential template for an article that doesn't include video content

https://invis.io/2BABGDY6N#/217957908_Desktop_Article_Template
