### ISSUE TITLE
Magazine: implement landing page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#202]
**View:** https://github.com/ubyssey/ubyssey-dispatch-theme/blob/magazine/ubyssey/views.py#L393-L398

**Template:** https://github.com/ubyssey/ubyssey-dispatch-theme/blob/magazine/ubyssey/templates/magazine/landing.html

**Comment by psiemens** [comment]
@floriecai @bennylojf 

For now, I think it might be easiest to code the template with fake articles (hard-code the images, headlines, etc). That way we can focus on getting the design right and just add the content in later. Does that sound good?

**Comment by floriecai** [comment]
Sounds good
