### ISSUE TITLE
Magazine: implement footer

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#204]
**Template:** https://github.com/ubyssey/ubyssey-dispatch-theme/blob/magazine/ubyssey/templates/magazine/footer.html

**Comment by stanley-park** [comment]
Will there be separate footers for the landing page and the articles? If so instead of "Issue" I can change it to "Article" if we want something like that when it's not the landing page

**Comment by psiemens** [comment]
@oscartu2 I think we can just use the same for both!
