### ISSUE TITLE
Can't close search bar with click

### ISSUE THREAD

**Issue by luceliu** [ubyssey/ubyssey-dispatch-theme#216]
'escape' works but not intuitive

**Comment by bennylojf** [comment]
I think the problem is in Search.jsx. I've spent some time trying things from here: http://stackoverflow.com/questions/32553158/detect-click-outside-react-component but to no avail. 

Any ideas?

**Comment by psiemens** [comment]
@bennylojf Maybe we could try this?

https://github.com/Pomax/react-onclickoutside

**Comment by bennylojf** [comment]
That seems really complex.....I tried that tutorial but got lost.

What about this approach: https://gyazo.com/e2c4631701a5742834700927042af5b9? It's from http://stackoverflow.com/questions/23821768/how-to-listen-for-click-events-that-are-outside-of-a-component

I'm trying that but I can't get the render() part right. Do you have any suggestions for that?

**Comment by psiemens** [comment]
Here's some more information that should help solve this issue:

You should be able to close the search bar by clicking anywhere outside the container, but right now the only way to close the bar is by pressing `esc`.

At first I thought this was an issue with React, but then I realized that we actually show/hide the search bar with jQuery.

Right now the code that handles the show/hide of the search bar is here: https://github.com/ubyssey/ubyssey-dispatch-theme/blob/staging/ubyssey/static/src/js/main.js#L80-L85

You'll notice that you can close the search bar by calling `$searchform.hide()`.

We just need to make it to so `$searchform.hide()` gets called when the user clicks outside of the search bar.

Here's some jQuery code I found that handles clicking outside of an element -- it should be a good place to start!

```js
$(window).click(function() {
//Hide the container if visible
});

$('#container').click(function(event){
    // Prevent container from being hidden if click is inside 
    event.stopPropagation();
});
```
