### ISSUE TITLE
Position of link to store is hidden in the homepage

### ISSUE THREAD

**Issue by jimmyhli** [ubyssey/ubyssey-dispatch-theme#223]
The scroll bar should be eliminated - the link to store gets hidden.

I suspect the problem might arise when you are using devices with smaller screens

![ss](https://cloud.githubusercontent.com/assets/18109953/23031120/b8b2a660-f424-11e6-8873-34193cd7878c.png)

**Comment by jimmyhli** [comment]
@psiemens Not sure if a new issue should be opened up or should we consider this as the leftover from the original task?

**Comment by bennylojf** [comment]
I got rid of the scroll bar, but when the page is compressed, the link to the store is cropped. Is that what you want? I pushed my changes to a branch - please take a look.

**Comment by jimmyhli** [comment]
Thanks for the quick fix! I'll take a look after my exam later today.

**Comment by psiemens** [comment]
Good catch @HaoyuanLi 

Thanks for taking care of it @bennylojf!

**Comment by bennylojf** [comment]
@HaoyuanLi ?

**Comment by jimmyhli** [comment]
@bennylojf Your fix's good and I did notice the problem that when the page is compressed, the link to the store get cropped (and when the page gets compressed more, more stuff get cropped)..  do you think should store be given priority? I wonder how is it like on a 13.3-inch mac/windows device cause myself am on 15.6, I think if things don't get cropped on devices whose screens are larger than 13.3 it should be fine as thats what most people are at.. and @psiemens what do you think?

**Comment by bennylojf** [comment]
@HaoyuanLi we can use bootstrap to prevent things from getting cropped?

**Comment by psiemens** [comment]
@HaoyuanLi @bennylojf 13 inches seems like a good cutoff to me, but since screen resolutions vary it's usually better to make things responsive for all possible screen sizes.

In this case the cropping is expected -- we're working on a redesign of the header bar that will add more room for links, but for now @bennylojf 's fix is fine!

I'll check out the code and merge. Thanks again!
