### ISSUE TITLE
Stories seem to align differently

### ISSUE THREAD

**Issue by jimmyhli** [ubyssey/ubyssey-dispatch-theme#263]
![2017-05-29 2](https://cloud.githubusercontent.com/assets/18109953/26541319/101f26a0-440a-11e7-8c0c-067d1bed99ce.png)

**Comment by i-ron-y** [comment]
This seems to be another example of the same phenomenon:

![article alignment](https://user-images.githubusercontent.com/31330116/32088575-3d963eba-ba99-11e7-8225-2d17c1538e73.jpg)

Some observations (at least with regards to my example):

For default articles, the photo is on the right hand side, and the textual content on the left, under the article headline, which spans the width of both the text and the photo. This whole block (headline, photo, and text) is in the centre of the screen.

The full-width articles (the articles that seem to be aligning differently), on the other hand, seem to allow the photo to be in various specific different locations... but it seems that the article's headline, photo, and text, as a whole group, is still in the aligned in the centre of the screen.

What I'm not understanding is what a full-width article is and what its purpose is. Should the layout of a full-width article be changed to conform to the style of the default article?

**Comment by JamieRL** [comment]
There are a number of templates offered to allow editors to present their articles in different styles. As for some of the alignment  issues I believe its fixed for within the article and infinite scroll is gone as well so we shouldn't be seeing two articles on top of one another anymore
