### ISSUE TITLE
Events article sidebar widget

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#268]
**Prerequisite:** #269 

We want to create a new widget that displays a single event in the article sidebar. For now, you can make it so the same event is displayed on every article, but in the future we'll either randomize it or allow editors to choose which events show up.

The widget and zone should be defined in `ubyssey/widgets.py`

You can consult the style guide for styling/css: https://ubyssey.github.io/styles/events

**Mockup:**
![event-sidebar-widget](https://user-images.githubusercontent.com/2547035/27869293-76ba2bbe-616d-11e7-84d8-29920c6d8c48.png)

**Comment by Axel-Jacobsen** [comment]
Howdy @psiemens 

Should the zone be just a sidebar zone, like the following? 
```
class Sidebar(Zone):

    id = 'sidebar'
    name = 'Sidebar'
```
What else should be included in the zone? Thanks!

**Comment by psiemens** [comment]
Yep, that works! Maybe call it `ArticleSidebar`

**Comment by Axel-Jacobsen** [comment]
Sounds good!
