### ISSUE TITLE
Fix pending event padding

### ISSUE THREAD

**Issue by Axel-Jacobsen** [ubyssey/ubyssey-dispatch-theme#276]
<img width="287" alt="screen shot 2017-07-12 at 3 43 04 pm" src="https://user-images.githubusercontent.com/20530172/28143130-e7eb5e56-6718-11e7-9fdb-9aea2250ca29.png">
<img width="384" alt="screen shot 2017-07-12 at 3 42 59 pm" src="https://user-images.githubusercontent.com/20530172/28143129-e7ea1366-6718-11e7-9439-8b47be701f39.png">

**Comment by psiemens** [comment]
Wrong repo - move to https://github.com/ubyssey/dispatch/

**Comment by Axel-Jacobsen** [comment]
@psiemens wouldnt they make more sense in ubyssey-dispatch-theme because they are both strictly CSS issues?
