### ISSUE TITLE
Implement author pages

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#28]

**Comment by jimmyhli** [comment]
Is this a collection of reports produced by the same person?

**Comment by psiemens** [comment]
@HaoyuanLi Yep.

It's already partially finished. If you want to take this, let's talk about it sometime this week and I'll show you what needs to be done.

**Comment by jimmyhli** [comment]
Lol sure! I didn't really see your reply till now...

**Comment by psiemens** [comment]
No worries @HaoyuanLi. Let's chat next week!

**Comment by jimmyhli** [comment]
Yea
