### ISSUE TITLE
homepage: upcoming events widget scrolls with page for a bit

### ISSUE THREAD

**Issue by joncppl** [ubyssey/ubyssey-dispatch-theme#295]
thereby substantially highlighting it but without being obnoxious.

**Comment by psiemens** [comment]
I thought this functionality was for the article sidebar widget?

**Comment by joncppl** [comment]
Perhaps I'm mistaken. I'll double check with Ron.

I have a prototype in this branch: https://github.com/ubyssey/ubyssey-dispatch-theme/tree/scrolling-events-widget
