### ISSUE TITLE
Investigate Facebook Live platform

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#299]
- Conduct some preliminary research into the Facebook Live platform

Guiding questions:
- What is the best way to embed a Facebook Live video on our website?
- What needs to be done to integrate FB Live with our current widget platform?
- Is there a way to include live comments on our website?

Please document your findings in this issue

**Comment by Axel-Jacobsen** [comment]
19. Live API policies
https://developers.facebook.com/policy

**Comment by joncppl** [comment]
`From: https://developers.facebook.com/docs/plugins/embedded-video-player#faq
Can I use the Graph API video property embed_html?
No, you should not use the property embed_html. Use the Embedded Video Player plugin instead!`

Therefore I think we should develop a component for the embedded video player that will use `data-href=https://www.facebook.com/video.php?v={id}`, where id is the id of the live-video.

**Comment by psiemens** [comment]
> Therefore I think we should develop a component for the embedded video player that will use data-href=https://www.facebook.com/video.php?v={id}, where id is the id of the live-video.

Agreed. That sounds like a good approach.

**Comment by joncppl** [comment]
I think we don't even need the API, just get the public stream URL placed into our component.

Likewise with the comment component
https://developers.facebook.com/docs/plugins/comments/
