### ISSUE TITLE
Improve event detail page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#300]
- [x] Design new mockup for event detail page
- [x] Implement new design

**Comment by Axel-Jacobsen** [comment]
19. Live API, 2. "Don’t use the API to stream directly from a mobile phone or tablet camera to Facebook."
https://developers.facebook.com/policy

**Comment by psiemens** [comment]
Design mockup is finished, Zeplin screen is here: https://zpl.io/aNgJRnb
