### ISSUE TITLE
Footer floating up

### ISSUE THREAD

**Issue by Axel-Jacobsen** [ubyssey/ubyssey-dispatch-theme#312]
<img width="1279" alt="screen shot 2017-08-24 at 12 04 59 pm" src="https://user-images.githubusercontent.com/20530172/29683821-82799b8c-88c4-11e7-9b02-f75ee3e200fb.png">

I can't quite remember the fix, though I have done it before. The issue is persistent in Safari and Chrome.

**Comment by Jedeu** [comment]
Hey I'd like to take a look at this issue please!
