### ISSUE TITLE
Event edit page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#323]
We want to add a page that allows event submitters to edit their events after they've been submitted.

After an event is approved, the submitter should receive a secret link that brings them to a pre-populated form, which they can use to make further edits to the event.

**Comment by Axel-Jacobsen** [comment]
I think that this been solved? And do i happen to have access to the live version of dispatch?

**Comment by Axel-Jacobsen** [comment]
Whoops! Forgot that I had this issue. I'll take care of it, hopefully I can get it done within a week? I'll keep y'all updated.
