### ISSUE TITLE
Video / Twitter embed offset in articles

### ISSUE THREAD

**Issue by Axel-Jacobsen** [ubyssey/ubyssey-dispatch-theme#328]
<img width="968" alt="screen shot 2017-09-04 at 4 29 29 pm" src="https://user-images.githubusercontent.com/20530172/30040046-577658bc-918e-11e7-8ce5-c95e9cc1eb57.png">
<img width="953" alt="screen shot 2017-09-04 at 4 29 20 pm" src="https://user-images.githubusercontent.com/20530172/30040047-579fb036-918e-11e7-92af-156797fc4e73.png">

 see link below for example:

https://www.ubyssey.ca/culture/why-meme-culture-loves-fireflies/?ref=frontpage)

**Comment by bf777** [comment]
I'd like to work on this!

**Comment by psiemens** [comment]
@bf777 Sure thing! Just assigned it to you.

**Comment by psiemens** [comment]
Fixed by @bf777
