### ISSUE TITLE
Getting Started Tutorial

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#332]
Add a block of text to the homepage that says "I completed the getting started tutorial", along with a random number between 1 and 10. It should look something like this:

![screen shot 2017-09-17 at 11 43 43 am](https://user-images.githubusercontent.com/2547035/30523831-7ca3e276-9b9d-11e7-9b4b-ba6a95ed00f0.png)

**The rest of the tutorial will walk you through how to implement this task.**

**Comment by psiemens** [comment]
I'd like to work on this!

**Comment by bf777** [comment]
I'd like to work on this!

**Comment by BenGHolmes** [comment]
I'd like to work on this!

**Comment by lorenzodb1** [comment]
I'd like to work on this!

**Comment by achin797** [comment]
I'd like to work on this!

**Comment by aprilzhong** [comment]
I'd like to work on this!

**Comment by rithikha** [comment]
I'd like to work on this!

**Comment by victorhyde** [comment]
I'd like to work on this!

**Comment by svmvnthvs** [comment]
I'd like to work on this!
