### ISSUE TITLE
Do not display old events

### ISSUE THREAD

**Issue by Axel-Jacobsen** [ubyssey/ubyssey-dispatch-theme#336]
<img width="660" alt="screen shot 2017-09-21 at 9 11 25 am" src="https://user-images.githubusercontent.com/20530172/30706370-eef2bf3e-9eac-11e7-8550-5e93e3edf231.png">

Just saw this event for Nora en Pure in the pit on Sept. 7. Should we automatically delete old events? E.g. the day or week after the event occurs, it could be automatically deleted. 
Thoughts?

**Comment by psiemens** [comment]
I think we should still keep them in the database, but maybe find a way to hide them from displaying on the site.

**Comment by Axel-Jacobsen** [comment]
Ill change it to "Dont display old events"?
