### ISSUE TITLE
Photos not displaying on author pages

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#338]
A photo should be displaying to the left of the name on this page: https://www.ubyssey.ca/authors/moira-wyton/

The URL it's trying to load is `images/moira-wyton-bio.jpg`, when really it should be `https://ubyssey.storage.googleapis.com/media/images/moira-wyton-bio.jpg`

It looks like the page is missing the `{% static %}` template tag.

**Requirements:**
- Make use of the `static` template tag to properly render the image 

Example:
```django
{% load static %}
<img src="{% static "my_app/example.jpg" %}" alt="My image"/>
```

**Comment by Jedeu** [comment]
Hey I'd like to take a look at this issue please!

**Comment by psiemens** [comment]
Sure thing @Jedeu. Were you able to get your dev environment configured?

**Comment by psiemens** [comment]
Implemented by @svmvnthvs
