### ISSUE TITLE
Display estimated reading time at top of article

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#342]

**Comment by i-ron-y** [comment]
From where will we be getting the estimated reading time? Keep track of how long previous readers spent on the page and calculate the average?

**Comment by jimmyhli** [comment]
I think you can just count the words

**Comment by psiemens** [comment]
@i-ron-y I meant to add more details to the description -- my bad. 

I was thinking we could calculate the reading time in minutes, using the article word count and average reading speed (40 words per minute).

This actually used to be a feature but got removed from Dispatch, so I was hoping we could add it back to this repo. The code for it still exists in the template, but since `article.get_est_reading_time` no longer exists, it doesn't get rendered.

Here's the template code: https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/templates/article/default.html#L23-L28

**Comment by psiemens** [comment]
Implemented by @BenGHolmes
