### ISSUE TITLE
Results on events page should be ordered by event start_time

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#343]
Events aren't being displayed in chronological order:

![screen shot 2017-09-25 at 12 30 27 pm](https://user-images.githubusercontent.com/2547035/30826989-62144fe4-a1ed-11e7-8c57-75e8036ae829.png)

**Requirements:**
- Update the events view to sort results by `start_time`

**Comment by i-ron-y** [comment]
Working on this.
