### ISSUE TITLE
Entire event box should be clickable

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#344]
Right now, event boxes only have links on the photo and title. Users should be able to click anywhere on the container to go to the event page.

![screen shot 2017-09-25 at 12 32 35 pm](https://user-images.githubusercontent.com/2547035/30827035-9efd23a4-a1ed-11e7-8074-33fafc09cd4a.png)

**Comment by i-ron-y** [comment]
When the entire container is clickable, should we still keep the separate links on the photo and title? Redundancy?

**Comment by i-ron-y** [comment]
Belated "I'd like to work on this!" - already got it working.

**Comment by psiemens** [comment]
@i-ron-y I think we can remove the other links -- no need for redundancy
