### ISSUE TITLE
"Advertise" page seems to be broken on Firefox.

### ISSUE THREAD

**Issue by i-ron-y** [ubyssey/ubyssey-dispatch-theme#347]
[The Advertise page](https://www.ubyssey.ca/advertise/)

Unless the _very_ barebones look of that page is deliberate, something's broken there.

Some screenshots:

**The top of the page:**

![some screenshots of advertise page top](https://user-images.githubusercontent.com/31330116/30840466-49da55ec-a22c-11e7-8b25-8d9f645a8f6d.png)

**The bottom of the page:**

![some screenshots of advertise page end](https://user-images.githubusercontent.com/31330116/30840467-49dcce76-a22c-11e7-87d4-1f6caefe6f68.png)

[EDIT: This seems to be the case only on my computer's Firefox browser. I have since tested this in Chrome on my computer, and Safari on my phone - they look okay to me. Maybe it's a problem with Firefox instead of the Ubyssey site...]

**Comment by psiemens** [comment]
I can't seem to reproduce this. Is Firefox showing any errors in the console? I wonder if it's trying to load an older cached version of the page.

**Comment by i-ron-y** [comment]
I'm finding these errors on the console:

```
Loading failed for the <script> with source “https://ubyssey.storage.googleapis.com/static/js/advertise-1.3.2.js”.  advertise:685
Loading failed for the <script> with source “https://securepubads.g.doubleclick.net/gpt/pubads_impl_151.js”.  advertise:1
```

**Comment by i-ron-y** [comment]
Okay, I figured out the issue. I have AdBlocker Ultimate on in my Firefox window - for some reason, it seems to be blocking everything on that one page. Shall I close this issue?

**Comment by psiemens** [comment]
Ah, that makes sense. I assume it's because contains the word `advertise`. 

Let's keep it open for now -- I can try renaming the file.
