### ISSUE TITLE
Correct day should be highlighted for events page 

### ISSUE THREAD

**Issue by Axel-Jacobsen** [ubyssey/ubyssey-dispatch-theme#348]
Taken at 2017-09-25 at 6:03:23 pm

<img width="554" alt="screen shot 2017-09-25 at 6 03 23 pm" src="https://user-images.githubusercontent.com/20530172/30837758-30eed248-a21c-11e7-86e6-0c6b40a481f0.png">

This is probably a time zone issue

**Comment by i-ron-y** [comment]
Getting the same issue on the actual events page, but funnily enough, on my local version, the correct date (i.e. 25) is highlighted.

**Comment by psiemens** [comment]
The timezone got reset to to UTC (8 hours ahead of us) when we moved to app engine, so the day rolls over at 4pm PST. This is something I can fix in the app engine config

**Comment by Axel-Jacobsen** [comment]
just wondering if this has been fixed?

**Comment by psiemens** [comment]
@Axel-Jacobsen No it hasn't. I need to figure out the App Engine timezone configuration
