### ISSUE TITLE
Uneven column widths on hompage

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#352]
These columns should all be the same width:

![screen shot 2017-09-27 at 3 05 34 pm](https://user-images.githubusercontent.com/2547035/30940289-710c5556-a395-11e7-81e9-efd69850e1d3.png)

**Comment by i-ron-y** [comment]
This isn't an issue in Firefox for some reason.

![firefox homepage column width](https://user-images.githubusercontent.com/31330116/30951831-dcb75992-a3d9-11e7-8864-98c615f1e30a.PNG)

I see the uneven column widths in Chrome though.

[EDIT: Correction, it seems that the middle column is in fact slightly narrower than the left and right columns even in Firefox. It just doesn't look as obvious.]

**Comment by i-ron-y** [comment]
So this was an issue for not just the homepage, but also the news/culture/opinion/sports/etc pages. I think I've fixed it now - made a PR.
