### ISSUE TITLE
Pop up menu covers title bar and can't be closed on mobile

### ISSUE THREAD

**Issue by victorhyde** [ubyssey/ubyssey-dispatch-theme#356]
![capture](https://user-images.githubusercontent.com/17039081/31148184-d5daeec0-a840-11e7-94de-7f63cf812b9d.PNG)
![capture2](https://user-images.githubusercontent.com/17039081/31148187-d7f2c17e-a840-11e7-9a90-42bec240148b.PNG)

**Comment by i-ron-y** [comment]
Which device/browser are you using? I'm not getting this issue on my iPhone (Safari).

**Comment by psiemens** [comment]
@i-ron-y It seems to break on most Android devices.
