### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by ubysseybiz** [ubyssey/ubyssey-dispatch-theme#370]
Button adjacent / inline with business office contact information "View the Digital Media Kit"

**Comment by jumbosushi** [comment]
@ubysseybiz  is this still an issue?

**Comment by ubysseybiz** [comment]
Googling "Ubyssey contact" yields old.ubyssey.ca as top result

Could you repoint "http://old.ubyssey.ca/contact-us/" to the corresponding
new site? Along with http://old.ubyssey.ca/staff/



*Ron Gorodetsky*
Business Manager*,* Ubyssey Publications Society

*p. *604 283 2024 *toll free *1 888 234 7726 ext 102 <1%20888%20234%207726>
*w.* ubyssey.ca
*e.* business@ubyssey.ca

*2209-6133 University Blvd, Vancouver BC*
<http://facebook.com/ubyssey>  <http://twitter.com/Ubyssey>
<http://instagram.com/ubyssey>

**Comment by jumbosushi** [comment]
Ah gotcha 
![image](https://user-images.githubusercontent.com/9669739/38529174-196ba1aa-3c18-11e8-9b18-ab8410665b5b.png)

**Comment by Rowansdabomb** [comment]
Has this issue been resolved?

**Comment by Rowansdabomb** [comment]
This issue appears to have been resolved
