### ISSUE TITLE
Show "Letter to the Editor" disclaimer at top of opinion letters

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#387]
We want to give editors the ability to add a disclaimer at the top of opinion letters so that our readers can easily tell the difference between submitted letters and actual news articles.

Something like this:

![screen shot 2017-11-14 at 11 38 33 am](https://user-images.githubusercontent.com/2547035/32800882-63092f86-c930-11e7-97d9-52af2030f712.png)

**Comment by ogadoury** [comment]
html to be added to 'ubyssey.ca/ubyssey/templates/article/default.html' 

```
<div class='disclaimer'>
   <p>This is a letter to the editor. Letters to the editor an be submitted to The Ubyssey's opinion editor. Include your name, address and daytime phone number. Try to keep letters to 150 words. Letters may be edited for length and clarity.</p>
   <button><a href="https://www.ubyssey.ca/submit-an-opinion/">Click here to submit your own!</a></button>
 </div>
```

css to be added to 'ubyssey.ca/ubyssey/static/dist/css/main-1.3.2.css

```
div.disclaimer {
  height: 20%;
  width: 98.4%;
  margin-top: 12px;
  margin-bottom: 6px;
  padding: 2.5px 5px 10px 10px;
  background-color: #3490d6;
  color: white;
  border-radius: 5px;
};

.disclaimer button.btn {
  background: #3490d6;
}
```
