### ISSUE TITLE
Display three rows of articles at top of section page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#388]
On the section page, we want to display three rows of articles instead of just one:

![screen shot 2017-11-14 at 11 42 58 am](https://user-images.githubusercontent.com/2547035/32801128-02ad31ea-c931-11e7-8d0d-0d4313a648b5.png)

**Comment by JamieRL** [comment]
This has been superseded by the subsections feature.
