### ISSUE TITLE
Allow support for print issue box on homepage

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#393]

**Comment by i-ron-y** [comment]
I threw together a simple hacky solution for extracting the URL and cover image of the latest print issue from https://issuu.com/ubyssey. As I said, hacky: right now, it's command-line run (and prints the URL and cover image URL onto console), not automated, and the Firefox window opened by Selenium WebDriver pops up annoyingly.

[Ubyssey Latest ISSUU Extractor](https://github.com/i-ron-y/ubyssey-latest-issuu-extractor)

Give it a look-see, maybe we can incorporate something like that into ubyssey.ca?

**Comment by psiemens** [comment]
@i-ron-y this is awesome! I assume Selenium is required because the Issuu webapp is JavaScript based? 

My only concern is whether this is feasible on a server without a GUI. Our app engine environment is pretty restricted as is, and I wouldn't be surprised if it simply doesn't support headless browsers.

I did a bit of poking around and found that Issuu has an RSS feed feature: https://developers.issuu.com/feeds/. Do you think this might make scraping the content easier?

**Comment by i-ron-y** [comment]
I used Selenium because of the dynamic JS content, yeah.

I hadn't thought about the RSS feed... that should definitely make things easier!
