### ISSUE TITLE
Photo credit bug(?) on the live version of ubyssey.ca

### ISSUE THREAD

**Issue by i-ron-y** [ubyssey/ubyssey-dispatch-theme#420]
Some (but not all) of the photo credits have a "File " in front of the person's name.

![photo credits bug - file](https://user-images.githubusercontent.com/31330116/36014917-00be0d44-0d21-11e8-83ce-3b79c4dd7c0d.PNG)

Examples with "File ":
- https://www.ubyssey.ca/opinion/ams-decoded-february-council-meeting/
- https://www.ubyssey.ca/opinion/mind-your-mind-you-arent-alone/
- https://www.ubyssey.ca/news/ams-passes-expulsion-policy/

Examples without "File ":
- https://www.ubyssey.ca/news/ubc-connects-lecture-series/
- https://www.ubyssey.ca/news/ubc-to-develop-indigenous-strategic-plan/
- https://www.ubyssey.ca/opinion/their-campus-vancouver-island/

**Comment by jumbosushi** [comment]
Looks like the weird strings are saved in db
```
use ubyssey;
select id,full_name from dispatch_person;
```

Wonder if it's being included somewhere :thinking:

**Comment by jumbosushi** [comment]
Fixed it on the db side
