### ISSUE TITLE
Mobile homepage header bar is not sticky.

### ISSUE THREAD

**Issue by i-ron-y** [ubyssey/ubyssey-dispatch-theme#422]
n/a

**Comment by jumbosushi** [comment]
This seems to be fixed now? @i-ron-y

**Comment by i-ron-y** [comment]
This is weird, but I had a look at the mobile version site on my computer and the header is sticky, but on my Safari phone browser (iPhone SE, iOS 11.2.5), it's not sticky. Not sure why.

EDIT: I've tried it on several of my family members' iPhones (different models, iOS), and the header is also not sticky.

**Comment by Rowansdabomb** [comment]
perhaps adding the following to the header class will fix it:
`transform: translate3d(0,0,0);`
source:
https://stanko.github.io/ios-safari-scroll-position-fixed/

**Comment by Rowansdabomb** [comment]
fixed in #527
