### ISSUE TITLE
Twitter embed has too much height

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#427]
Twitter embed have height that is too high so it  creates unnecessary space
[Example article](https://www.ubyssey.ca/news/ams-vp-admin-debate-recap-2018/)

![too_much_spacing](https://user-images.githubusercontent.com/9669739/36888092-def8812e-1da8-11e8-8a00-d849527e44d4.png)

**Comment by ganes1410** [comment]
@jumbosushi  can i do this?
