### ISSUE TITLE
Weird spacing in about partnership section

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#429]
Need to investigate where this is coming from

![emptyspot](https://user-images.githubusercontent.com/9669739/37000220-9389949a-2077-11e8-97b4-48e45a591647.png)

**Comment by ogadoury** [comment]
You're looking for it to look more like this?
<img width="921" alt="screen shot 2018-01-13 at 4 24 44 pm" src="https://user-images.githubusercontent.com/32474674/37322569-9e8d52b8-263b-11e8-9f2a-ce6ddf6a1f10.png">

**Comment by ogadoury** [comment]
You're just looking to have it look more like this?
<img width="566" alt="screen shot 2018-03-12 at 9 23 00 pm" src="https://user-images.githubusercontent.com/32474674/37322584-b7f1b3ca-263b-11e8-8575-22e6d0d738dc.png">
