### ISSUE TITLE
Tests for ArticleHelper

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#433]
Currently we don't have any python tests for [ArticleHelper](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/helpers.py) class.
As we implement new design in the future, having a test suite will help us develop new features faster.

This would be a great task for anyone who wanna dip their feet into python world :snake:

**Comment by aaronNgu** [comment]
I'd like to work on this
