### ISSUE TITLE
Long bullet point items covered by right-hand ads

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#47]
![](https://cloud.githubusercontent.com/assets/18159904/16966890/7a64b84a-4dbb-11e6-9885-ec6028562120.png)

**Comment by psiemens** [comment]
@annygakh If you finish #48, can you give this a try as well? They're pretty similar problems.

**Comment by psiemens** [comment]
Here's an example in the wild: http://ubyssey.ca/opinion/positively-sex-consent-will-make-you-better-in-bed/

**Comment by annygakh** [comment]
<img width="1025" alt="screen shot 2016-09-20 at 10 07 27 am" src="https://cloud.githubusercontent.com/assets/9780809/18680803/12d1f84c-7f1a-11e6-9656-97b47e718796.png">
So in the above example, the long bullet point items are not covered by ads (I have made sure to disable my ad blocker) but they are wider than the rest of the text which makes it look inconsistent, and that is what I should fix, correct?

**Comment by psiemens** [comment]
> So in the above example, the long bullet point items are not covered by ads (I have made sure to disable my ad blocker) but they are wider than the rest of the text which makes it look inconsistent, and that is what I should fix, correct?

@annygakh Yep, exactly!
