### ISSUE TITLE
Section Columns

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#490]
Give editors the ability to create and curate columns within their section. A column would be a group of related articles that is featured on the front page of the section, and would also have its own separate landing page. 

A column can have:
 - title
 - description
 - author(s)
 - image (maybe?)

In the admin panel, there should be a way to create and manage existing columns. Articles can be added to a column from the article edit page. 

On the frontend, the section page design should be updated to make room for columns, and a new design should be made for a column landing page (consult w/ editorial about this, especially Moira b/c it was her idea).

**Comment by JamieRL** [comment]
Added in PR #511
