### ISSUE TITLE
Optimize ttfb

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#497]
We should strive to get the ttfb for the ubyssey to average under 200ms. Currently the site ttfb for articles on ubc internet is +400ms.

**Comment by jimmyhli** [comment]
I'm interested in knowing a bit more about how ttfb is optimized!

**Comment by jimmyhli** [comment]
@Rowansdabomb I'm interested in knowing a bit more about how ttfb is optimized!

**Comment by Rowansdabomb** [comment]
We are looking into methods to optimise our ttfb. Currently we are considering creating a separate table in the database for published articles, however it is unclear as to how much speed up this will give us as we already index our articles via an is_published tag. Another thing we are looking into is optimising our article queries, which is somewhat django REST framework specific. I can give you more information as we start to implement these changes, but currently this issue is on the back-burner.

**Comment by Rowansdabomb** [comment]
Closing this as it has been moved to issue #562
