### ISSUE TITLE
mobile header spacer on desktop

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#535]
the mobile-header-spacer is taking up too much height on the frontpage of the site. 

![image](https://user-images.githubusercontent.com/19273530/44482747-1953d200-a5fe-11e8-9a54-34eb07d882a5.png)

**Comment by jimmyhli** [comment]
should it be changed to 0px instead

**Comment by Rowansdabomb** [comment]
I checked the user_agent for mobile request and disable the mobile header on non-mobile requests

fixed in #536
