### ISSUE TITLE
Add screenshot to README.md

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#544]
The README could use a little more love. Love to see the screenshot on top of the page!

**Comment by AyahRamahi** [comment]
Hello, I am a beginner . how can I help ?

**Comment by Rowansdabomb** [comment]
Hey there Ayah, have you signed up as a web volunteer? We are going to be setting up another web volunteer meeting for next week. I'll let you know what time as soon as its set up.

**Comment by AyahRamahi** [comment]
@Rowansdabomb How can I sign up for that ?

**Comment by Rowansdabomb** [comment]
Please send me your email address at rowan@ubyssey.ca
