### ISSUE TITLE
Reduce image  "From the Blog"

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#547]
We are serving hi-def images for our homepage 'From the Blog' section. 

![image](https://user-images.githubusercontent.com/19273530/45838003-81610b00-bcc5-11e8-8132-ba758c4a3994.png)

This is bad as larger images take longer to download and require more bandwidth.
Let's reduce their size.

**Steps to get started**

Look into the `Image` model located [here](https://github.com/ubyssey/dispatch/blob/develop/dispatch/modules/content/models.py#L442). Specifically look at the functions `get_absolute_url`, `get_medium_url`, and `get_thumbnail_url`. These functions return urls to different sizes of the same image. 

Now look at the django template located [here](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/templates/objects/articles/column.html#L4). Notice the use of `get_medium_url`. Update this template to render the thumbnail image instead.

**Comment by kellylawrence** [comment]
@Rowansdabomb Tackled this in https://github.com/ubyssey/ubyssey.ca/pull/565.
