### ISSUE TITLE
Improve homepage algorithm

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#55]
The homepage sorting algorithm currently puts too much emphasis on the `reading_time` attribute, which means that articles from a long time ago sometimes how up on the front page. We should set some sort of time limit to prevent this.

**Comment by mchernoff** [comment]
Improved get_frontpage with an extra ordering clause. Articles from more than two weeks ago are sorted  to the bottom. 

Changed frontpage_speed branch name to frontpage_test (for both issues).

**Comment by psiemens** [comment]
@mchernoff can you open a pull request with `staging`?
