### ISSUE TITLE
Rendering issue on Safari on Mobile

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#553]
One of our editors told us that there is a rendering issue on Safari on iOS when you go to [this article ](https://www.ubyssey.ca/culture/the-hatch-mediocre/)

![received_296300060957009](https://user-images.githubusercontent.com/9669739/45841414-99895800-bcce-11e8-95e7-4b586fb81b52.jpeg)

**Comment by acsikos** [comment]
Could not reproduce.  Tested on a iPhone 6 running version 11.3.1.  Please comment on the iPhone used and version the iPhone is running

**Comment by jumbosushi** [comment]
Thanks for the investigation! I'll ask around our editors tmrw to check which version their device is on

**Comment by jumbosushi** [comment]
@psiemens do you see this issue on your mac?

**Comment by psiemens** [comment]
@jumbosushi Nope, not in any browser 😕
