### ISSUE TITLE
Design for /about

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#554]
Currently, our [about page](https://www.ubyssey.ca/about/) is simply a block of text 😐.  Would love to see some design sprinkles for this page! (example about page: [metalab](https://metalab.co/company), [Stripe](https://stripe.com/about)

![image](https://user-images.githubusercontent.com/9669739/45841713-8034db80-bccf-11e8-9c8c-4cb840342136.png)

**Comment by ogadoury** [comment]
I can do this one!

**Comment by jumbosushi** [comment]
@ogadoury Awesome! Let me know if you need any help

**Comment by ogadoury** [comment]
[https://github.com/ubyssey/ubyssey.ca/tree/554-design-for-about](url)
