### ISSUE TITLE
Fix the cookie disclaimer

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#555]
We have a cookie disclaimer to comply with EU regulations. If you are interested, you can read more about it [here](https://www.cookiebot.com/en/cookie-consent-banner/?gclid=CjwKCAjwio3dBRAqEiwAHWsNVStXbF6jN047UlDgYtOPerVmcliqi-P2Tz9fy7wJDrd9Ag3lFK_N0hoCb8QQAvD_BwE).

Our header is positioned fixed over the cookie disclaimer, partially obscuring it. 

![image](https://user-images.githubusercontent.com/19273530/45841035-77dba100-bccd-11e8-971b-f28829a13ac1.png)

Let's ensure that our cookie disclaimer is always fully visible.

**Steps to get started**
You can find the sass stylesheet for the cookie disclaimer [here](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/static/src/styles/components/_cookie-disclaimer.scss)

The Cookie Disclaimer is actually implemented as a React component. You probably won't need to change the component itself, but for the sake of completeness you can find the source code for the CookieDisclaimer.jsx file [here](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/static/src/js/components/CookieDisclaimer.jsx)

You can either move the cookie disclaimer so it sits below the header. Or you may position the disclaimer to render at the bottom of the screen. Ensure your fix accounts for **both the desktop and mobile** styles of the site. 

**Note**
Because the cookie disclaimer's visibility is dependent on a cookie itself, You may want to disable cookies while working on this. 

If you are testing on google chrome, You can also delete the cookie by entering the browser inspector `ctrl-shift-i` or right click in the browser and select `inspect` from the drop down. Then, in the inspector window, navigate to the Application -> Cookies -> https://www.ubyssey.ca. Find the Cookie with the name `cookie_disclaimer` and delete it's **value**. You will likely have to do this multiple times.

**Comment by kellylawrence** [comment]
@Rowansdabomb Would there be any issues with setting `<div id="cookie-disclaimer"></div>` in the [base.html template](https://github.com/ubyssey/ubyssey.ca/blob/909a1cb1064c4320d25e1dcf850f29c2a5cf5a09/ubyssey/templates/base.html#L105) as the last rendered element? (After `<div id="content-wrapper">`)

From some quick testing, this would keep the disclaimer fixed below the rest of the page content for both mobile and desktop, without requiring any CSS changes. (Bottom placement of cookie disclaimers also seems to be a common design pattern these days, for what it's worth.)

EDIT: I should add that I also have a snippet of CSS that should work as an alternative, if the `#cookie-disclaimer` element can't be moved. It would keep the disclaimer at the top, but I had also been looking into CSS changes that would place it at the bottom if that is preferred.

**Comment by Rowansdabomb** [comment]
The cookie disclaimer needs to be viewable on the screen at all times until it has been clicked through. I believe if you move the tag below the content wrapper you would have to scroll the disclaimer into view.

**Comment by kellylawrence** [comment]
@Rowansdabomb I may not have been clear with what I meant to propose for the fix. Below will show the placement of `<div id="cookie-disclaimer"></div>` in the DOM, and how it appears on the page for desktop and mobile.

<img width="1440" alt="screen shot 2018-10-02 at 10 31 42 am" src="https://user-images.githubusercontent.com/815248/46352540-6e88f780-c630-11e8-8d83-b1c37afb2094.png">
<img width="1440" alt="screen shot 2018-10-02 at 10 33 11 am" src="https://user-images.githubusercontent.com/815248/46352541-6e88f780-c630-11e8-8362-cc2e5514de52.png">

The disclaimer stays "fixed" to the bottom fo the page, and doesn't require any scrolling to view. It also works properly when you scroll to the bottom of the page, where footer content will appear above it as expected.

This seems to work as intended, and I've experienced no issues in testing across the latest versions of Chrome, FF, Safari, or Edge, for mobile or desktop.

**Comment by Rowansdabomb** [comment]
This is a excellent solution

**Comment by Rowansdabomb** [comment]
Resolved in #569
