### ISSUE TITLE
Web Team sticker

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#556]
Would be amazing if we can get our own custom laptop sticker for web team. 

For example, [rbnb project](https://twitter.com/robinson_es/status/915220688717455360) at Airbnb have their own sticker with consistant brand design language, or even [something like Supreme](https://dribbble.com/shots/3688897-Shopify-Stickers)
![image](https://user-images.githubusercontent.com/9669739/45843462-91ccb200-bcd4-11e8-90ce-5b6df47f8d71.png)

Or the company called Mercari have their python team sticker

![image](https://user-images.githubusercontent.com/9669739/45888088-13265200-bd72-11e8-92d5-4cd62de9db00.png)

**Comment by jane-thea** [comment]
I can take this one for yall

**Comment by psiemens** [comment]
Oooh this is dope!
