### ISSUE TITLE
Design for 404 page

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#559]
404 page could use more design touch. The wording could be more welcoming as well

![image](https://user-images.githubusercontent.com/9669739/45889941-92b62000-bd76-11e8-8372-9cd98f866f01.png)

### Steps to load 404 locally:
1. Change `DEBUG=True` to `DEBUG=False` on [this line](https://github.com/ubyssey/ubyssey.ca/blob/develop/_settings/settings-local.py#L25) from `setting.py` file
2. Edit [this line](https://github.com/ubyssey/ubyssey.ca/blob/develop/local-dev/docker-compose.yml#L41) in your `docker-compose.yml` file to be the following: 
```
command: bash -c "cd ubyssey.ca && python manage.py runserver --insecure 0.0.0.0:8000
```
3. Stop and restart your docker servers

**Comment by jane-thea** [comment]
Any way I can take a crack at this one? (I'm not super familiar with github so if you could point me to where I need to find the source code that'd be super)

**Comment by jumbosushi** [comment]
Awesome! I've added `404.scss` file in `redesign-404` branch for you to get started

**Comment by brittkhat** [comment]
Steps to recreate 404 need to be edited, above ones are out-of-date

**Comment by wnguye03** [comment]
started the design outline on Figma, but need help with illustration. Once done I can start coding
