### ISSUE TITLE
Implement full article archive

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#56]
Quoted from Sam (news editor):

> I was wondering if there was any way that eventually, readers to our website could go way further back in the specific sections. For example, when you click on news there are quite a few articles right now that you can scroll down as boxes, which looks great, but then when you eventually get to the bottom, there could be an arrow to take you to a separate page deeper into the archives or whatever!

I'd like to build a complete, searchable archive for all articles (and possibly images) on our website. It's an important piece that's currently missing. We'll have to discuss the design in more detail, but I'm picturing a page that allows you to search and filter by section, year, month, etc.

@mchernoff Do you think this is something you could take on eventually?

**Comment by mchernoff** [comment]
I'm thinking there'd be a ubyssey.ca/archive section, that could be accessed via the link menu, or a button that shows up when you scroll to the absolute bottom of an articles section
 (i.e. "Want more articles? View our archive")

I'll start work on the front-end for now but we can discuss the specifics if needed.

**Comment by psiemens** [comment]
> a button that shows up when you scroll to the absolute bottom of an articles section

I like the sound of that! Let's chat about the design/layout more in person sometime this week.
