### ISSUE TITLE
Create a continue reading button on mobile

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#560]
The ubyssey should have a continue reading button perhaps 1.5 scroll-views down an article page on mobile. The user should click through the continue reading button to reveal the article. 

![continue reading](https://user-images.githubusercontent.com/19273530/45910518-b69d5400-bdbe-11e8-9e8e-68082f04828a.png)

The picture above is just a quick mock up. The final result should match the aesthetic of the site. 

A continue reading button allows mobile users to quickly assess whether they want to read the article, and if not more easily access the content below (instead of scrolling the entire article). This hopefully results in better user engagement!

Ideally, this functionality should only appear if a user has navigated directly to the article, e.g. from a social media link, and not if the navigated there from ubyssey.ca directly.

**This issue is not complete. Please do not begin working on this issue until this disclaimer has been remove**

**Comment by evilwombat** [comment]
To future web developers who want to add "continue reading" buttons to their articles -

I think I speak for all readers when I say that we hate such garbage.

Our engagement is very transactional - we clicked through to an article, so we want to read the article; we don't care what comes after. As soon as the article is over, we're closing the tab. Any attempt to further claw at our attention is at best futile or irritating, and makes us reach for the element hiding helper.
