### ISSUE TITLE
Fix sizing of "Trending" news

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#570]
Currently, "Trending" page breaks the frontpage. Need to resize the `div`

![screen shot 2018-10-03 at 6 31 21 pm](https://user-images.githubusercontent.com/9669739/46510374-6df18c00-c7fd-11e8-8fe0-bfde9b8a07c1.png)

**Comment by Rowansdabomb** [comment]
this is up in #573
