### ISSUE TITLE
Update React Version

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#580]
Currently, our React version is 0.13.3 and the latest React version right now is v16.

React have an official guide on how to upgrade the versions for each breaking change:
- [from 0.13.3 to 0.14](https://reactjs.org/blog/2015/10/07/react-v0.14.html#upgrade-guide)
- [from 0.14 to 0.15](https://reactjs.org/blog/2016/04/07/react-v15.html#upgrade-guide)
- [breaking changes in 0.15.5](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html)
- [from 0.15.6 to 0.16](https://reactjs.org/blog/2017/09/26/react-v16.0.html#upgrading)

We should upgrade incrementally so 0.13 -> 0.14 -> 0.15 -> 0.15.5 -> latest 0.16
Before we start migrating, I think it would be a good idea to add tests for our critical React components. Without the tests, we really can't tell what broke until we see it in production (#589)

Another concern is our dependencies. Some packages might not support older / newer React version so we would need to do research on those as well.

**Comment by jimmyhli** [comment]
Interested in more details 😆
