### ISSUE TITLE
Create a map template for upcoming soccer nationals

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#583]
map, with team logos over the team origins. When logos are clicked, a unique article is loaded on the page.

**Comment by jumbosushi** [comment]
Visuals Idea

![img_20181025_125323](https://user-images.githubusercontent.com/9669739/47528173-55531f80-d859-11e8-8748-e0662179be41.jpg)

**Comment by Rowansdabomb** [comment]
this is up in #596
