### ISSUE TITLE
Cookies disclaimer breaks article page on mobile

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#586]
The cookie popup has a few problems:
- It doesn't close when I tap "continue" (edit: apparently this only happens on the featured article template)
- It extends the height of the page instead of sticking to the bottom
- If I scroll ON the popup, it pushes the rest of the content up and freezes my mobile browser

This makes it *very* difficult to read mobile articles - I would fix asap!

My phone specs: iPhone XS, Safari, iOS 12.0.1

![img_1021](https://user-images.githubusercontent.com/2547035/47687634-6758f900-db9e-11e8-9720-aac0e213b7a5.PNG)

**Comment by Rowansdabomb** [comment]
Should be fixed in #587
