### ISSUE TITLE
Cookies do not persist

### ISSUE THREAD

**Issue by Rowansdabomb** [ubyssey/ubyssey-dispatch-theme#588]
Cookies do not seem to persist past the browser session. 

It looks like the cookie expiry dates are past dated to 1969, this is probably the source of the issue.

![image](https://user-images.githubusercontent.com/19273530/47824910-51793e80-dd2c-11e8-9a48-aae7ae400d04.png)

**Comment by jimmyhli** [comment]
This `YSC` cookie is set by youtube.com though, so I doubt if there's anything we can do on our end. I believe this `YSC` simply stands for `Youtube Session Cookie` (though I can't find anything credible to back my assumption), and is designed to be deleted at the end of a browser session. 😃 

I've seen some sources that indicate that this YSC has something to do with sharing videos and stuff, but I don't know about that for sure.

**Comment by Rowansdabomb** [comment]
Sorry if that image is unclear, `YSC` is not the cookie in question. The only cookies we are concerned about currently are the `cookie_disclaimer` and `ubyssey_site_visit` cookies.

**Comment by jimmyhli** [comment]
Oh, sorry. `YSC` caught my attention because it was highlighted 🤣 

Do you mind taking a look at https://github.com/ubyssey/ubyssey.ca/pull/591

**Comment by Rowansdabomb** [comment]
fixed in #591
