### ISSUE TITLE
Podcast is missing from mobile header dropdown

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#593]
Would be fixed by adding
```python
<li><a href="{% url 'podcasts' 'episodes'%}">Podcasts</a></li>
```
after [this line](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/templates/headers/mobile.html#L18) in `mobile.html`

![image](https://user-images.githubusercontent.com/9669739/47968643-b204c600-e021-11e8-9132-fb6e4c2c51d5.png)

**Comment by Rowansdabomb** [comment]
fixed in #590
