### ISSUE TITLE
Create index url for /podcasts

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#594]
In [urls.py](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/urls.py#L74), podcast url is currently defined as:

```python
# Podcasts
url(r'^podcast/(?P<slug>[-\w]+)', theme.podcast, name='podcasts'),
```

Would be cleaner if we use pattern that we use for magazines url

```python
# Guide to UBC
url(r'^guide/$', guide.landing, name='guide-landing'),
url(r'^guide/(?P<slug>[-\w]+)/$', guide.article, name='guide-article'),
```

Doing this allows templates to refer to podcasts as `{% url 'podcasts' %}` instead of `{% url 'podcasts' 'episodes' %}`

**Comment by jimmyhli** [comment]
This would involve writing a new `view` for podcasts I assume?
