### ISSUE TITLE
Add tests for React components 

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#598]
This test is so that we can upgrade our React version as stated in #580 

We have jasmine defined in our `package.json` file. I suggest we update to Jest since it is more widely used, provide [snapshot testing for UI](https://jestjs.io/docs/en/snapshot-testing), and almost compatible with jasmine syntax (which we have just 1 js test file :sweat_smile: )

**Comment by brittkhat** [comment]
Needs to be reassessed after wagtail migration for full scope. Tentative re-evaluation of issue scheduled for fall 2021.
