### ISSUE TITLE
Ask for reader involvement page

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#604]
ProPublica has a [page where they ask for more reader involvement](https://www.propublica.org/getinvolved/) when they want to write about a specific topic (for example [this one](https://www.propublica.org/getinvolved/have-you-seriously-considered-filing-for-bankruptcy) is looking for people who have bankrupted in the past.

![image](https://user-images.githubusercontent.com/9669739/48583271-8adcad00-e8db-11e8-91cd-3ec0fed69e7d.png)

 This page can replace [Twitter call out](https://twitter.com/moirawyton/status/1062844192743841792) that we do time to time. 

![image](https://user-images.githubusercontent.com/9669739/48581529-efe1d400-e8d6-11e8-9260-03ad7db880a2.png)

One feature specific request to have an anonymous file drop when they want to tip us with info.

**Comment by brittkhat** [comment]
Editors have the ability to create this feature within wagtail now
