### ISSUE TITLE
Better get involved page

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#605]
Our volunteer page could use more design love. Welcoming any styling ideas.

### Content 

![image](https://user-images.githubusercontent.com/9669739/48581822-b8bff280-e8d7-11e8-8401-d0f935fff69c.png)

### Header

Would be cool to also somehow make our header pop out a bit more to gain attraction

![image](https://user-images.githubusercontent.com/9669739/48581800-aba30380-e8d7-11e8-83c6-2e3928570c56.png)

**Comment by ogadoury** [comment]
I can take a go at this one!
