### ISSUE TITLE
Add "Add to Homescreen Button" 

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#606]
Some editors requested an app, but we can use PWA to achieve the same thing. 

Browsers automatically render add to the home button on mobile if the specific fields in `manifest.json` are met. Find what the requirements are in [this doc]!

Should look something like this but with our logo
![image](https://user-images.githubusercontent.com/9669739/48582174-a0040c80-e8d8-11e8-8fb5-efb53dfae9f8.png)

**Comment by cyborg-nomade** [comment]
hi there, i could try and work on this if no one else is doing it
