### ISSUE TITLE
Share to Reddit button

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#608]
A huge chunk of our traffic comes from Reddit, and some editors suggested us to make a share to Reddit button. From quick googling it looks like all we have to do is adding html blurb
```html
<a href="//www.reddit.com/submit?url=[Atricle URL]>
   <img src="[Image_source]" alt="reddit share" />
</a>	
```

**Comment by cyborg-nomade** [comment]
hi there, if no one else is working on this, i could try and develop this feature
