### ISSUE TITLE
Email newsletter subscription — most-read stories of the week

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#62]
We want to add a newsletter signup form that adds users to a Mailchimp email list. 

The form will appear in the footer of the website, as well as the article sidebar and possibly as the occasional popup. 

I'll take care of setting up the actual Mailchimp list, so you won't have to worry about that. Most of your work will be building/styling the form(s).

**Comment by jimmyhli** [comment]
Would this be done using drupal sth?

**Comment by psiemens** [comment]
@HaoyuanLi What do you mean?

**Comment by jimmyhli** [comment]
Ha! Im just not sure what to do about this? a sign up form? @psiemens

**Comment by JamieRL** [comment]
with mailchimp setup we can just create a page in dispatch and add links to the header/footer/wherever
