### ISSUE TITLE
Add lazy loading to home page

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#629]
Our home page can benefit from lazy loading. For example, notice how pictures on [Bustle website](https://www.bustle.com/) loads pictures as you scroll down. [Read this Google tutorial](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/) to get started

**Comment by brittkhat** [comment]
Attempt to implement did not pass review in terms of function and efficiency and ease of implementation
