### ISSUE TITLE
Introduce yapf for Python code formatting

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#631]
## What is yapf

[Yapf](https://github.com/google/yapf) is a tool by Google to auto format their python code.

## Why we should have it

Similar reason as #621 to minimize the chance of new contributor losing momentum when making a PR by getting comments on syntax fixes.

**Comment by brittkhat** [comment]
no longer use dispatch and checked for relavancy
