### ISSUE TITLE
Add empty state in /events page

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#647]
## What behavior were you expecting?

In the /events page, when the user clicks on the week that have no scheduled events, it should show a message in the line of "there is no scheduled event for this week"

## What actually happened?

![image](https://user-images.githubusercontent.com/9669739/55267023-09a80600-523d-11e9-8d6b-241169db56bc.png)

Currently if you click on the week when there are no events scheduled, it doesn't show any message (and looks like it's still loading content)

## Steps to reproduce

1. Go to https://www.ubyssey.ca/events/
2. Click around weeks until there's a week with no events submitted yet

**Comment by d1vyanshu** [comment]
Hi! I would like to solve this issue. Can you help me by telling which file should I specifically look at for this issue ?

**Comment by Rowansdabomb** [comment]
Hey @d1vyanshu, You can find the django template that would render the `no events submitted yet` in [events.html](https://github.com/ubyssey/ubyssey.ca/blob/eb4b406b462fdee5b36790fc22642f6e97f418ec/ubyssey/templates/events/events.html#L67). 

You may notice that the events shown are the elements of the `events` array, which you can find in [events/views.py](https://github.com/ubyssey/ubyssey.ca/blob/eb4b406b462fdee5b36790fc22642f6e97f418ec/ubyssey/events/views.py#L191).

**Comment by d1vyanshu** [comment]
I have tried twice to create and submit pull request for this. The changes that I have made are working perfectly for me but don't know what tests it is failing. Please help!
