### ISSUE TITLE
Article from 2018 shows up in 2015 Archive

### ISSUE THREAD

**Issue by razvannesiu** [ubyssey/ubyssey-dispatch-theme#652]
The article is the following:
Title: Relate to Senate: What to expect in the November meeting
URL: https://www.ubyssey.ca/opinion/relate-to-senate-november-2018/

## What behavior were you expecting?
I was expecting this article not to show up on the 2015 archive. (I already checked the 8th page of the 2018 archive, and this article shows up there as well - as it should).

![Screenshot (90)](https://user-images.githubusercontent.com/11470906/56841725-4ec35600-6844-11e9-81cc-f1d30cb103cd.png)

## Steps to reproduce
1. Go to Archive (at the bottom of the page).
2. Select 2015.
3. The first article that shows up is from 2018.

## What was your environment like?
Windows 10, Chrome 73.0.3683.103.

**Comment by brittkhat** [comment]
Closing issue for now as recent updates to Archive page functionality seem to have resolved this bug.
