### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#655]
Our app is running with Python 2.7 right now, but [it will not be maintained past 2020](https://pythonclock.org/). Let's update it to Python 3.7, and it also let us update Django to 2.0 as well. 

Initial work is done by @Rowansdabomb on branch `407-python-3`

**Comment by ghost** [comment]
I updated ubyssey.ca dir. Should I also update bin, dispatch, and lib since they also contain python files?
