### ISSUE TITLE
Ad in sidebar overlaps article contents once it becomes sticky

### ISSUE THREAD

**Issue by blx** [ubyssey/ubyssey-dispatch-theme#681]
## What behavior were you expecting?

- Box ad in sidebar sticks to top of content area upon scroll, but does not overlap any other sidebar or footer elements.
- When I scroll to the bottom of the page and then back to the top, the sidebar ad should first become sticky to the top but then return to normal flow when I've scrolled up past its top.
- When I scroll to the bottom of the page, and "Suggested Articles" and "Most Popular This Week" come into view, the sidebar ad should not be sticky on top of those sections, but should constrain itself to flow with the article body's scrolling.

## What actually happened?

The power of fixed positioning corrupts fixedly. (Once the sidebar ad acquires `position: fixed`, it doesn't give it up.) It overlaps onto the footer when scrolled down, and when scrolled back to the top, it overlaps the h1, article top image, and other stuff vertically in line above it.

Video: https://drive.google.com/file/d/1moMh83AwSJYNCcoyt82RqsaAzeqZpvw6/view?usp=sharing

## Steps to reproduce

1. Open an article page that contains a sidebar ad (`.o-advertisement`) (I saw this one: [link](https://www.ubyssey.ca/news/BC-killers-found-dead/?ref=frontpage))
2. Scroll down the page until the ad is scrolled into or beyond the header
3. Continue scrolling to the bottom and see that the ad is overlapping "Suggested Articles" and "Most Popular This Week"
4. Scroll back to the top and see that the ad is covering the article's headline, share/tweet buttons, and top-right pull image if applicable.

I wonder if something in [article.jsx#stickyAds()](https://github.com/ubyssey/ubyssey.ca/blob/develop/ubyssey/static/src/js/article.jsx#L88-L132) is not watching correctly for un-sticking conditions?

## What was your environment like?

Chrome 75 on OS X Sierra

**Comment by brittkhat** [comment]
unable to reproduce
