### ISSUE TITLE
RSS feed is not updating

### ISSUE THREAD

**Issue by NotWoods** [ubyssey/ubyssey-dispatch-theme#794]
## What behavior were you expecting?

RSS feed shows current articles

## What actually happened?

RSS feed contains no items

## Steps to reproduce

Open https://www.ubyssey.ca/rss/

Sorry, unsure if this is caused by the theme or dispatch itself.

**Comment by keeganland** [comment]
Will take a look when I get the chance

**Comment by brittkhat** [comment]
Scope out with Wagtail, and investigate current demand for RSS Feed

**Comment by SamuelmdLow** [comment]
Fixing issue in this branch:

https://github.com/ubyssey/ubyssey.ca/tree/794-rss-samlow
