### ISSUE TITLE
Categories missing/broken

### ISSUE THREAD

**Issue by ihciem** [ubyssey/ubyssey-dispatch-theme#938]
## What behavior were you expecting?
Categories bar to show up

## What actually happened?

<img width="989" alt="Screen Shot 2022-02-04 at 12 00 09" src="https://user-images.githubusercontent.com/45521929/152595506-113b5a92-1cff-4d8d-87f4-4409bb338b09.png">

**Comment by lua0204** [comment]
This is a super important issue as I need to add the Black History month article under a subhead and I need them to be easily accessible
