### ISSUE TITLE
Twitter and Facebook Previews 

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#939]
Twitter and Facebook Previews not appearing as expected. Nothing appears to be showing on twitter.
Early feedback from users point to title tags potential requirement for title to show up.

<img width="570" alt="Screen Shot 2022-02-01 at 10 27 28 AM" src="https://user-images.githubusercontent.com/83617860/152595619-677b84fc-0424-4b9e-bf1f-4a65abb13b64.png">

**Comment by ihciem** [comment]
Mostly fixed by @keeganland
