### ISSUE TITLE
Images stretching on homepage

### ISSUE THREAD

**Issue by ihciem** [ubyssey/ubyssey-dispatch-theme#940]
## What actually happened?
<img width="851" alt="Screen Shot 2022-02-04 at 9 28 50 AM" src="https://user-images.githubusercontent.com/45521929/152596970-fed64918-16f0-4aab-8a73-f25df4750a28.png">

**Comment by keeganland** [comment]
This is likely caused by someone setting the wagtail resize rules incorrectly in some templates

See: https://docs.wagtail.org/en/stable/topics/images.html
