### ISSUE TITLE
Website seems to be disconnected from Google analytics

### ISSUE THREAD

**Issue by lua0204** [ubyssey/ubyssey-dispatch-theme#941]
The view count on our google analytics is not working for some reason. It still seems to be connected but the count is way too low and not accounting for most articles to be correct. 

## What behavior were you expecting?
Something to look like this for a week:
<img width="1579" alt="Screen Shot 2022-02-04 at 4 05 09 PM" src="https://user-images.githubusercontent.com/87782858/152619177-89c43d8e-2ec7-4d88-820b-8b89d435fb46.png">

## What actually happened?

<img width="1368" alt="Screen Shot 2022-02-04 at 4 04 48 PM" src="https://user-images.githubusercontent.com/87782858/152619187-d59094b7-0753-4e59-8ddc-23a3c4af0515.png">

**Comment by keeganland** [comment]
I have been operating under the assumption that the broken meta tags are what broke this. Tried to replicate their functionality as best I could today. We'll see if it works
