### ISSUE TITLE
Front page headers seem to not work

### ISSUE THREAD

**Issue by lua0204** [ubyssey/ubyssey-dispatch-theme#942]
## What behavior were you expecting?

Expected to be taken to the news home page if clicking on news, but page seems to only refresh our ubyssey homepage

![image](https://user-images.githubusercontent.com/87782858/152623537-313495e3-ef32-4584-91f9-238a1bd48c47.png)

## What actually happened?

Ubyssey.ca got refreshed instead of being taken to the news page

## What was your environment like?

IOS?

**Comment by ihciem** [comment]
Issue fixed with HP changes. Closing
