### ISSUE TITLE
Photo's on Articles Dissappear

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#950]
This may be linked to a previous issue where photos within an article do not show up. Awaiting more information. Content in question is previously published articles from dispatch. Checking with editorial staff if this issue is also occurring with newly published articles through wagtail.

Examples from staff where photos and poems are no longer visible:
https://www.ubyssey.ca/culture/Culture-Collection-of-Winter-Haikus/
https://www.ubyssey.ca/culture/December-10-poem/
https://www.ubyssey.ca/culture/Calming-things-while-studying/
https://www.ubyssey.ca/culture/Sonnet-reflections-on-an-in-person-return/

**Comment by brittkhat** [comment]
Update: new articles currently being published are impacted by the issue. A live test was just done by Tianne(she/her)

**Comment by ihciem** [comment]
Related to #964
