### ISSUE TITLE
Update digital print issue on home page

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#951]
Current digital print issue accessed through home page is dated as July 27, 2021. Will make inquiries for additional info before dev meeting.

**Comment by brittkhat** [comment]
Currently this is updated by hard-coding into the html, as a maintenance task this needs to be accomplished. As a feature, we should automate this process and it would be ideal if we could accomplish this within the current development cycle.

**Comment by keeganland** [comment]
I have isolated the HTML in question into its own template/streamfield block as part of doing other tasks. This means it gets its own context variables and can be turned into a user-editted feature relatively easily

**Comment by brittkhat** [comment]
Task complete
