### ISSUE TITLE
Drafts that were meant to be unpublished appear on website

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#952]
Notes from Keegan's initial investigation from slack: 

"Articles technically didn't exist in Dispatch, only revisions to articles. "How did Dispatch know that two revisions were revisions of one article?" It... didn't. So how could it tell if an article was published? Well, it could tell if a specific revision was published ever at any point. Could it tell if it was subsequently unpublished? No, because nothing linked any revision to the subsequent revisions except that we pretended they were the same article. Which they never were. (And this is only describing one possible"

Example links provided by editorial staff:
https://www.ubyssey.ca/news/ams-vaccine-mandate-draft/?fbclid=IwAR3xB38zgE-_AR319l44NVlq7gy8bd49K_WTInt51ceN2RtVp5MSVBPOop8 

https://www.ubyssey.ca/news/ubc-vaccine-declaration-verification/?fbclid=IwAR3QqHBlb5hUFBuIEmHuyl8osENYple5NoCZAmYtX2HYxIanyczyTitthsQ

*note links may already be deactivated from the articles being unpublished

**Comment by brittkhat** [comment]
There is a high probability that dateless articles were not supposed to be published and its a buggy behavior left over from the dispatch migration of archived drafts/articles. To our knowledge this is not impacting current wagtail publications. In dispatch there were article revisions but not necessarily a true hard copy of an article.

**Comment by ihciem** [comment]
Mostly manually resolved (articles meant to remain unpublished were manually unpublished). Hard to know if 100% fixed, but no further actions for dev. Closing
