### ISSUE TITLE
ImageBlocks contain junk data from Dispatch migration

### ISSUE THREAD

**Issue by keeganland** [ubyssey/ubyssey-dispatch-theme#964]
Our Wagtail ImageBlocks copied data from Dispatch's "Image embeds". Unfortunately, it turns out Dispatch apparently would render Image embeds with a caption field containing the string `['auto']` as a blank string. Because Wagtail's caption fields do not share this behaviour, there are plenty of images currently accidentally captioned with "['auto']"

Every ImageBlock on the site should be inspected and this data removed. Will be difficult because ImageBlocks do not correspond to an SQL table.

**Comment by brittkhat** [comment]
If you find an article with images that have junk captions you can edit and delete the data.
