### ISSUE TITLE
Wagtail scheduled publishing feature

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#981]
There is an option to schedule when an article is published through wagtail's cms for the website. Investigate if it is deactivated or buggy.

**Comment by brittkhat** [comment]
Investigate and inquire wagtail for further information
[wagtailcms.slack.com](http://wagtailcms.slack.com/)

**Comment by GabrielPRomero** [comment]
Any update on this ?

**Comment by brittkhat** [comment]
https://docs.wagtail.org/en/v2.4/reference/pages/theory.html#scheduled-publishing
https://docs.wagtail.org/en/v2.4/reference/management_commands.html#publish-scheduled-pages
https://cloud.google.com/appengine/docs/legacy/standard/java/config/cronref-yaml

**Comment by brittkhat** [comment]
Workflow:

1. Draft is completed and approved for scheduled publishing
2. Enter Go Live: Date/Time in Settings Tab
3. Hit Publish. 
4. Article status will be scheduled
5. Web Development runs python management commands: 
      Current: ./manage.py publish_scheduled_pages
      Django 4.1: ./manage.py publish_scheduled

To Do: 
create automation: cron task google cloud server?

**Comment by FireBoyAJ24** [comment]
After the new changes to the homepage, the above workflow will not be feasible as the editors have to physically add the new top articles to the homepage. This was done on purpose to prevent the guide articles from covering our homepage and pushing the more relevant articles to the top.

**Comment by SamuelmdLow** [comment]
You can schedule a cronjob with https://console.cloud.google.com/cloudscheduler/

**Comment by SamuelmdLow** [comment]
The best option seems to be specifying cronjobs to google app engine with a `cron.yaml` file 

https://cloud.google.com/appengine/docs/legacy/standard/java/config/cron-yaml
