### ISSUE TITLE
Embedded graphs within articles scale to entire screen

### ISSUE THREAD

**Issue by ihciem** [ubyssey/ubyssey-dispatch-theme#988]
## What behavior were you expecting?

For the embedded items to keep the same width (and auto adjusted height) as the article (i.e. the text).

## What actually happened?

[https://www.ubyssey.ca/news/breaking-down-ubcs-329-billion-202223-budget/](https://www.ubyssey.ca/news/breaking-down-ubcs-329-billion-202223-budget/)

<img width="967" alt="Screen Shot 2022-04-07 at 3 12 34 PM" src="https://user-images.githubusercontent.com/45521929/162334261-6452a42e-89c4-456b-9394-c2d9fcbedd11.png">

**Comment by ihciem** [comment]
`style="width: 960px; height: 966.857px; transform: scale(1); transform-origin: 0px 0px 0px;"`

Note: transform: scale(1); resizes the element to full width ([mdn web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale))

Found the above line within the code (in Firefox code inspector) within the inserted html (raw HTML block from the CMS).

**Comment by brittkhat** [comment]
Article redesign, have resolved this issue
