### ISSUE TITLE
Change 'static' to 'static_src' on docker installation

### ISSUE THREAD

**Issue by Danisa-R** [ubyssey/ubyssey-dispatch-theme#989]
Change 'static' to 'static_src' on docker installation page under "How to build static files with Gulp" https://code.ubyssey.ca/installation/docker

**Comment by brittkhat** [comment]
Referring to documentation

**Comment by deacon8** [comment]
This was fixed in the volunteer repo. Should we close?

**Comment by FireBoyAJ24** [comment]
I have changed the static to static_src [here](https://code.ubyssey.ca/installation/wagtail-setup). At this location,
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/9dcbf568-5cb3-4c68-a3ec-ab9bbfc682e7)


The node_modules are located in the static_src and not in the static folder
