### ISSUE TITLE
Ad blocker creates huge empty space on the right side of homepage

### ISSUE THREAD

**Issue by Danisa-R** [ubyssey/ubyssey-dispatch-theme#990]
If user has adblocker on, 1/3 of the home page is blank. Space can be used to prop up 'Digital print issue' column
<img width="1346" alt="Screen Shot 2022-04-12 at 9 54 33 PM" src="https://user-images.githubusercontent.com/69412310/163103114-ec83e538-2878-4e10-a4e7-56e59a85f670.png">

**Comment by brittkhat** [comment]
This will be addressed with some Front-end design choices and is linked to other work currently in progress.
