### ISSUE TITLE
Dev Environment - DB Basic Framework PT.1

### ISSUE THREAD

**Issue by brittkhat** [ubyssey/ubyssey-dispatch-theme#994]
Using a fresh Database, re-create a basic development environment easy to install and small in size for volunteers and new employees.

Part 1- Export and create seed from dev db for distribution
Part 2 -  Create a sql seed from current database for article content to populate as needed dev environments

Purpose: Ease in onboarding new staff and volunteers, should container and local db get deleted developers had an easy quick and fresh install available without modifications or a huge database that is time consuming to pull from.

**Comment by SamuelmdLow** [comment]
Made new issue for this
