### ISSUE TITLE
New Archive Page

### ISSUE THREAD

**Issue by keeganland** [ubyssey/ubyssey-dispatch-theme#995]
The Archive page is supposed to be an archive of all student-created content. The overwhelming majority of student created content is in the form of ArticlePages. But students also take photos and make videos and other things. It has therefore been a frequent request to make the ArchivePage and the AuthorPage capable of handling

The traditional solution within The Ubyssey was to perform a nightmarishly complex SQL query that queries on several tables then joins those tables and then to perform a search on this query to insert "headings" and only then paginate the result. A particularly strange choice was to try to use the exact same logic for the ArchivePage and AuthorPage with just a slightly different query. (The front end for these indeed looked almost the same! It made the back end barely manageable, however).

This worked terribly and slowly, and the Archive and Author pages were a constant source of headaches. To make it so that these pages could be used for any of the desired features, I restricted the scope to only displaying ArticlePage content.

However, this unsurprisingly generated complaints (as it should, since it was removing features). A solution that was planned: Wagtail has a feature called "Routable Pages" that allow the incorporation of different view logic on what is in the page hierarchy considered the same page. The different view logics on the same page implies that we could create a link that says, say, "Photos" on the Archive page and run a query only after this click on the photos available on the site. This would allow us to keep the Archive Page one page (and so not spread out the relatively complex templating it requires), but attach requests to specific user actions, so we don't get a single abnormally complex request.

Here's a wagtail tutorial on routable pages:

https://www.youtube.com/watch?v=W2oHKiAYl3U

**Comment by FireBoyAJ24** [comment]
Notes from 16th May 2023 meeting:

1. The archive page has marketplace as section filter which has no contents.
2. The archive page does not have the 2020, 2021 and 2022 spoof magazines.
3. Filters(Years="All years", section="All", Order by="Oldest"),
 How we run
 by Charlotte Alden 10 months, 3 weeks ago, A guide to The Ubyssey for potential sources by Charlotte Alden 10 months, 3 weeks ago and Ubyssey student marketplace. That is not the oldest article.
4. The sections are not properly formatted. 
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/7a495d8b-ccaf-48e2-b9a9-2e4f922b13d7)
5. Dispatch, Peter and Taargus (a writer) has made test sites that are currently on the Ubyssey website. 
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/bef76573-bd07-4aec-96ed-7fa2fc8b6d82)
![image](https://github.com/ubyssey/ubyssey.ca/assets/63443017/c88f024f-b813-4185-8c8b-d8f329d874af)
6. At page https://ubyssey.ca/archive/?page=4&order=oldest, the description does not crop to the screen size.


5th June 2023 (Jay speaking):
1. To solve the above issues, I will open up separate issues for each of them as they are not directly related to the main issue Keegan has brought up.
2. The pull request should only solve Keegan's issue to ensure that it is easier to cycle back the problems with any future issues with the solution today.
