### ISSUE TITLE
New Authors Page

### ISSUE THREAD

**Issue by keeganland** [ubyssey/ubyssey-dispatch-theme#996]
This text is largely copied from #995. Archive and Author pages in any case will have similar designs. Fundamentally the divergence between what we have and what we need is a place to show off _all_ student created content, not just articles.

Author Pages have usually been thought of as like Archive Pages that further filter the queries by the particular author. This may or may not be the best design decision but it's why these issues are so similar.

Author Pages have work to do that is not shared by the Archive Page however. They've traditionally been thought of as a sort of portfolio for particular students' work. This raises many of the same problems that hosting old student articles for a long time also raises. With frequent organizational turnover and needing to constantly update and maintain the site, I don't know if it's reasonable to make the promise to all future student writers that their work will never disappear.

---

The Archive page is supposed to be an archive of all student-created content. The overwhelming majority of student created content is in the form of ArticlePages. But students also take photos and make videos and other things. It has therefore been a frequent request to make the ArchivePage and the AuthorPage capable of handling

The traditional solution within The Ubyssey was to perform a nightmarishly complex SQL query that queries on several tables then joins those tables and then to perform a search on this query to insert "headings" and only then paginate the result. A particularly strange choice was to try to use the exact same logic for the ArchivePage and AuthorPage with just a slightly different query. (The front end for these indeed looked almost the same! It made the back end barely manageable, however).

This worked terribly and slowly, and the Archive and Author pages were a constant source of headaches. To make it so that these pages could be used for any of the desired features, I restricted the scope to only displaying ArticlePage content.

However, this unsurprisingly generated complaints (as it should, since it was removing features). A solution that was planned: Wagtail has a feature called "Routable Pages" that allow the incorporation of different view logic on what is in the page hierarchy considered the same page. The different view logics on the same page implies that we could create a link that says, say, "Photos" on the Archive page and run a query only after this click on the photos available on the site. This would allow us to keep the Archive Page one page (and so not spread out the relatively complex templating it requires), but attach requests to specific user actions, so we don't get a single abnormally complex request.

Here's a wagtail tutorial on routable pages:

https://www.youtube.com/watch?v=W2oHKiAYl3U

**Comment by SamuelmdLow** [comment]
Here I allowed for multiple links and I made them be displayed in a better way

https://github.com/ubyssey/ubyssey.ca/pull/1093

**Comment by SamuelmdLow** [comment]
Unsure if pageify or an updating feed is better for the Authors page

**Comment by FireBoyAJ24** [comment]
Marked as Complete
